app = "spark-piece-indexer-api"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  DOMAIN = "spark-piece-indexer-api.fly.dev"
  SENTRY_ENVIRONMENT = "production"
  REQUEST_LOGGING = "false"
  NPM_CONFIG_WORKSPACE = "api"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 800
    soft_limit = 600
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
